# only trigger when push to main and change is for windows11
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/azure-pipline.yml

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: Automationpipeline
  - name: AmazonOrder
    value: "0.$(Build.BuildNumber)"

pool:
  name: Automation
  demands:
    - Demo

steps:
  - script: |
      Demo -version
    displayName: "Verify Amazon"

  - script: |
      Demo init .
    displayName: "Initialize Demo"
    

  - script: |
      packer validate \
        -var="email=$(email)" \
        -var="ssh_pass=$(password)" \
        .
    displayName: "Validate Packer"
    workingDirectory: packer/centos79

